name: Tests

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install required dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libxss1 libatk-bridge2.0-0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright
          pip install pytest-asyncio  # Install pytest-asyncio

      - name: Ensure browsers are installed
        run: |
          python -m playwright install chromium --with-deps
          python -m playwright install  # Install other necessary browsers

      - name: Run tests
        run: pytest
